theme: jekyll-theme-time-machine
title: welcome to my site
description:  this is a multi-informational site which includes current events, politics, 
              surfing, skateboarding, girls, guys, cars, travel and really anything i 
              find of interest
